remote_theme: pages-themes/minimal@c27a30c
#remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: Laboratorio de Instalación Sonora SPTM
description: La instalación sonora como medio de investigación y de expresión
  artística.
logo: img/sesion11/foto7.jpg
show_downloads: false
