remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme
title: Laboratorio de Instalación Sonora SPTM
description: La instalación sonora como medio de investigación y de expresión
  artística.
show_downloads: false
